### ISSUE TITLE
Build: Make caps sentence case

### ISSUE THREAD

**Issue by vikaspotluri123** [swapagarwal/swag-for-dev#108]
Currently tags are all lower case:

![image](https://user-images.githubusercontent.com/4383564/46708841-47b95b00-cc06-11e8-8a3f-099ad34bfced.png)

They would look better if they were `Sentence cased`

**Comment by aslafy-z** [comment]
This can be achieved by using css:
```css
p.sentence-case::first-letter {
  text-transform: uppercase;
}
```
```html
<p class="sentence-case">this string has a CAPITAL first-letter</p>
```
